spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:cookietest
    driver-class-name: org.h2.Driver
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create

#https://springdoc.org/v2/#properties
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    display-request-duration: true
    path: /swagger-ui
    filter: true
  show-actuator: true
