services:
  db:
    image: postgres:16.4
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: some-service
      POSTGRES_PASSWORD: some-service
      POSTGRES_DB: some-service
